const { ipcRenderer } = require('electron');
const io = require('socket.io-client');
const { Tutorial } = require('./tutorial');
const { SoundManager } = require('./sound');

// ════ 설정 ════
const SERVER_URL = 'https://hellowee-server.onrender.com';
const CHAR_SIZE = 256;          // 스프라이트 원본 크기 (256px로 그리기)
const DISPLAY_SIZE = 128;       // 화면에 보이는 크기 (CSS)
const FPS = 10, GRAVITY = 0.5;
const FLOOR_Y = window.innerHeight - DISPLAY_SIZE;
const BUBBLE_DURATION = 4000, EMPTY_BUBBLE_DURATION = 3000;
const CLICK_THRESHOLD = 5, DBLCLICK_TIME = 300;
const WHISPER_ATTENTION = 5, CHAT_ATTENTION = 30, MOUSE_IDLE_TIME = 3000, CHASE_SPEED = 3;
const INTERACT_DIST = 40, THROW_SPEED_THRESHOLD = 800, WAVE_LEAVE_DURATION = 1200;
let settingPin=true, settingAttention=true, settingBubble=true, settingSound=true;
const sfx = new SoundManager();
function playSound(name) { if (settingSound) sfx.play(name); }
const LAYER_ORDER=['body','clothes','mouth','eyes','hair','accessory'];
const PARTS_OPTIONS={body:['default','light','medium','dark'],eyes:['round','cat','sleepy'],mouth:['smile','neutral','pout'],hair:['short','long','ponytail'],clothes:['hoodie','shirt','dress'],accessory:['none','hat','glasses','ribbon']};
const ANIM_FRAMES={idle:4,walk:6,fall:2,grabbed:2,land:2,thrown:3,wave:6,sit:4,nod:4,jump:5};
const RANDOM_ACTIONS=['wave','sit','nod','jump'];
const EMOJIS=['👋','😂','❤️','👍','😭','🔥','🎉','🤔','😍','🙄','🐾','✨'];
const STATUS_LIST=['🟢 온라인','🟡 자리비움','🟠 밥 먹는 중','🔴 일하는 중','🟣 회의 중','⚫ 방해금지'];
const imageCache={};
function getPartImage(l,o,a){if(o==='none')return null;const k=`${l}/${o}/${a}`;if(!imageCache[k]){const i=new Image();i.src=`sprites/${k}.png`;imageCache[k]=i;}return imageCache[k];}
const myChar={x:window.innerWidth/2,y:100,vx:0,vy:0,state:'fall',dir:1,frame:0,frameTimer:0,isGrabbed:false,forcedGrab:false,attentionGrab:false,name:'guest',status:'',parts:{body:'default',eyes:'round',mouth:'smile',hair:'short',clothes:'hoodie',accessory:'none'}};
const otherChars={};let unreadChat=0,unreadWhisper=0,chatHistory=[],whisperHistory=[];let currentRoom=null,isRoomOwner=false;
ipcRenderer.on('auth-data',(event,data)=>{if(!data)return;if(data.nickname)myChar.name=data.nickname;if(data.parts)myChar.parts=data.parts;document.getElementById('settingsNicknameVal').textContent=myChar.name;if(Tutorial.needsTutorial()){startTutorial();}else{tryAutoReconnect();}});
function tryAutoReconnect(){try{const Store=require('electron-store');const store=new Store({name:'hellowee-auth'});const lastRoom=store.get('lastRoom');if(lastRoom&&lastRoom.code&&lastRoom.roomName){connectSocket();socket.on('connect',()=>{socket.emit('join-room',{code:lastRoom.code,roomName:lastRoom.roomName,name:myChar.name,parts:myChar.parts},(res)=>{if(res.success){currentRoom=res.code;updateLobbyUI();}else{openPhone('lobby');}});});}else{openPhone('lobby');}}catch(e){openPhone('lobby');}}
let mousePos={x:window.innerWidth/2,y:FLOOR_Y},lastActivityTime=Date.now(),mouseIsIdle=false,hasGrabbedMouse=false;
document.addEventListener('mousemove',(e)=>{mousePos.x=e.clientX;mousePos.y=e.clientY;lastActivityTime=Date.now();if(mouseIsIdle&&hasGrabbedMouse&&myChar.attentionGrab){mouseIsIdle=false;myChar.attentionGrab=false;myChar.forcedGrab=false;myChar.state='fall';myChar.vy=-3;myChar.vx=(Math.random()-0.5)*4;}});
document.addEventListener('mousedown',()=>{lastActivityTime=Date.now();sfx.init();});
function isAttentionMode(){return settingAttention&&(unreadWhisper>=WHISPER_ATTENTION||unreadChat>=CHAT_ATTENTION);}
// 캐릭터 캔버스: 원본 256px, 화면 128px
const myEl=document.createElement('canvas');myEl.width=CHAR_SIZE;myEl.height=CHAR_SIZE;myEl.className='character';myEl.style.width=DISPLAY_SIZE+'px';myEl.style.height=DISPLAY_SIZE+'px';document.body.appendChild(myEl);const myCtx=myEl.getContext('2d');
const alertBadge=document.createElement('div');alertBadge.className='alert-badge';alertBadge.textContent='!';alertBadge.style.display='none';document.body.appendChild(alertBadge);
function renderChar(ctx,el,char){const a=char.state||'idle',f=ANIM_FRAMES[a]||ANIM_FRAMES.idle,fr=char.frame%f;ctx.clearRect(0,0,CHAR_SIZE,CHAR_SIZE);ctx.save();if(char.dir===-1){ctx.translate(CHAR_SIZE,0);ctx.scale(-1,1);}let has=false;LAYER_ORDER.forEach(l=>{const o=char.parts?.[l];if(!o||o==='none')return;const img=getPartImage(l,o,a);if(img&&img.complete&&img.naturalWidth>0){has=true;ctx.drawImage(img,fr*CHAR_SIZE,0,CHAR_SIZE,CHAR_SIZE,0,0,CHAR_SIZE,CHAR_SIZE);}});if(!has){ctx.fillStyle='#ff6b9d';ctx.roundRect(16,16,CHAR_SIZE-32,CHAR_SIZE-32,24);ctx.fill();ctx.fillStyle='#fff';ctx.font='72px sans-serif';ctx.fillText('🐾',CHAR_SIZE/2-36,CHAR_SIZE/2+24);}ctx.restore();el.style.left=char.x+'px';el.style.top=char.y+'px';}
let activeEmptyBubble=null;
function showEmptyBubble(g,type,cb){removeEmptyBubble();const b=document.createElement('div');b.className='empty-bubble'+(type==='whisper'?' whisper':'');b.innerHTML=type==='whisper'?'🤫 ...':'💬 ...';document.body.appendChild(b);b.addEventListener('click',(e)=>{e.stopPropagation();removeEmptyBubble();if(cb)cb();});const t={el:b,charGetter:g};function up(){if(!b.parentElement)return;const p=g();b.style.left=(p.x+DISPLAY_SIZE/2)+'px';b.style.top=(p.y-44)+'px';}up();t.updatePos=up;t.timeout=setTimeout(()=>removeEmptyBubble(),EMPTY_BUBBLE_DURATION);activeEmptyBubble=t;ipcRenderer.send('set-ignore-mouse',false);}
function removeEmptyBubble(){if(activeEmptyBubble){clearTimeout(activeEmptyBubble.timeout);if(activeEmptyBubble.el.parentElement)activeEmptyBubble.el.remove();activeEmptyBubble=null;}}
let mouseDownPos=null,dragTarget=null,dragOffset={x:0,y:0},isDragging=false,lastClickTime=0,lastClickTarget=null,dragStartTime=0;
myEl.addEventListener('mousedown',(e)=>{e.stopPropagation();mouseDownPos={x:e.clientX,y:e.clientY};dragTarget='self';dragOffset.x=e.clientX-myChar.x;dragOffset.y=e.clientY-myChar.y;isDragging=false;dragStartTime=Date.now();ipcRenderer.send('set-ignore-mouse',false);if(myChar.attentionGrab){myChar.attentionGrab=false;myChar.forcedGrab=false;}});
document.addEventListener('mousemove',(e)=>{if(!dragTarget)return;const dist=mouseDownPos?Math.hypot(e.clientX-mouseDownPos.x,e.clientY-mouseDownPos.y):0;if(!isDragging&&dist>CLICK_THRESHOLD){isDragging=true;playSound('grab');if(dragTarget==='self'){myChar.isGrabbed=true;myChar.state='grabbed';myChar.vx=0;myChar.vy=0;}else if(socket)socket.emit('grab-other',{targetId:dragTarget});}if(isDragging){if(dragTarget==='self'){myChar.x=e.clientX-dragOffset.x;myChar.y=e.clientY-dragOffset.y;}else if(socket)socket.emit('drag-other',{targetId:dragTarget,x:e.clientX-dragOffset.x,y:e.clientY-dragOffset.y});}});
document.addEventListener('mouseup',(e)=>{if(!dragTarget)return;const now=Date.now();if(!isDragging){playSound('click');if(dragTarget==='self'){if(tutorial&&tutorial.isActive){if(tutorial.triggerAction('click-character'))return;}if(lastClickTarget==='self'&&(now-lastClickTime)<DBLCLICK_TIME){if(tutorial&&tutorial.isActive){tutorial.triggerAction('dblclick-character');}else{openPhone('home');}lastClickTarget=null;}else{const action=RANDOM_ACTIONS[Math.floor(Math.random()*RANDOM_ACTIONS.length)];myChar.state=action;setTimeout(()=>{if(myChar.state===action)myChar.state='idle';},1500);showEmptyBubble(()=>({x:myChar.x,y:myChar.y}),'chat',()=>openQuickChat(myChar.x+DISPLAY_SIZE/2,myChar.y-50,'chat'));lastClickTarget='self';lastClickTime=now;}}else{const tid=dragTarget,c=otherChars[tid];if(c)showEmptyBubble(()=>({x:c.x,y:c.y}),'whisper',()=>openQuickChat(c.x+DISPLAY_SIZE/2,c.y-50,'whisper',tid));}}else{const dt=now-dragStartTime,dist=mouseDownPos?Math.hypot(e.clientX-mouseDownPos.x,e.clientY-mouseDownPos.y):0,speed=dist/(dt||1)*1000;if(tutorial&&tutorial.isActive){tutorial.triggerAction('drag-character');}if(dragTarget==='self'){myChar.isGrabbed=false;if(speed>THROW_SPEED_THRESHOLD){playSound('throw');myChar.state='thrown';myChar.vx=(e.clientX-mouseDownPos.x)*0.15;myChar.vy=Math.min((e.clientY-mouseDownPos.y)*0.15,-3);}else{myChar.state='fall';myChar.vy=1;myChar.vx=0;}}else if(socket){if(speed>THROW_SPEED_THRESHOLD){playSound('throw');socket.emit('throw-other',{targetId:dragTarget,vx:(e.clientX-mouseDownPos.x)*0.1,vy:-3});}else socket.emit('drop-other',{targetId:dragTarget});}}ipcRenderer.send('set-ignore-mouse',true);dragTarget=null;mouseDownPos=null;isDragging=false;});
const quickChat=document.getElementById('quickChat'),quickChatInput=document.getElementById('quickChatInput'),quickChatLabel=document.getElementById('quickChatLabel');
let quickChatMode='chat',quickWhisperTarget=null;
function openQuickChat(x,y,mode,tid){quickChatMode=mode;quickWhisperTarget=tid||null;quickChatLabel.textContent=mode==='whisper'?`🤫 ${otherChars[tid]?.name||'???'}`:'💬 전체';quickChat.style.left=Math.min(x,window.innerWidth-260)+'px';quickChat.style.top=Math.max(y,30)+'px';quickChat.classList.add('visible');let emojiBar=quickChat.querySelector('.emoji-bar');if(!emojiBar){emojiBar=document.createElement('div');emojiBar.className='emoji-bar';emojiBar.style.cssText='display:flex;gap:2px;flex-wrap:wrap;margin-top:4px;';EMOJIS.forEach(em=>{const btn=document.createElement('button');btn.textContent=em;btn.style.cssText='background:none;border:1px solid #2a2a35;border-radius:8px;padding:4px 6px;cursor:pointer;font-size:14px;';btn.addEventListener('click',()=>{quickChatInput.value+=em;quickChatInput.focus();});emojiBar.appendChild(btn);});quickChat.appendChild(emojiBar);}quickChatInput.value='';quickChatInput.focus();ipcRenderer.send('set-ignore-mouse',false);}
quickChatInput.addEventListener('keydown',(e)=>{if(e.key==='Enter'&&quickChatInput.value.trim()&&socket){const m=quickChatInput.value.trim();if(quickChatMode==='chat')socket.emit('chat',{message:m});else if(quickWhisperTarget)socket.emit('whisper',{targetId:quickWhisperTarget,message:m});quickChatInput.value='';quickChat.classList.remove('visible');ipcRenderer.send('set-ignore-mouse',true);}if(e.key==='Escape'){quickChat.classList.remove('visible');ipcRenderer.send('set-ignore-mouse',true);}});
const phone=document.getElementById('phone'),phoneClose=document.getElementById('phoneClose'),phoneBack=document.getElementById('phoneBack'),phoneTitle=document.getElementById('phoneTitle');
const pages=document.querySelectorAll('.phone-page'),homeIcons=document.querySelectorAll('.home-icon');let currentPage='home';
const PAGE_TITLES={home:'🐾 Hellowee',chat:'💬 채팅',lobby:'🏠 로비',custom:'🎨 꾸미기',settings:'⚙️ 설정'};
function openPhone(p){currentPage=p||'home';phone.classList.add('visible');playSound('phoneOpen');ipcRenderer.send('set-ignore-mouse',false);switchPage(currentPage);hideAlert();}
function closePhone(){phone.classList.remove('visible');playSound('phoneClose');ipcRenderer.send('set-ignore-mouse',true);}
phoneClose.addEventListener('click',closePhone);
phoneBack.addEventListener('click',()=>{playSound('click');switchPage('home');});
homeIcons.forEach(i=>{i.addEventListener('click',()=>{playSound('click');switchPage(i.dataset.page);});});
function switchPage(p){currentPage=p;pages.forEach(pg=>pg.classList.toggle('active',pg.id==='page'+p));phoneTitle.textContent=PAGE_TITLES[p]||'🐾 Hellowee';phoneBack.classList.toggle('visible',p!=='home');if(p==='chat')renderChatMessages();if(p==='lobby')updateLobbyUI();if(p==='settings')document.getElementById('settingsNicknameVal').textContent=myChar.name;}
const chatMessages=document.getElementById('chatMessages'),chatPageInput=document.getElementById('chatPageInput'),chatPageSend=document.getElementById('chatPageSend');
const chatSubTabs=document.querySelectorAll('.chat-sub-tab');let chatSubTab='all';
chatSubTabs.forEach(t=>{t.addEventListener('click',()=>{chatSubTab=t.dataset.subtab;chatSubTabs.forEach(x=>x.classList.toggle('active',x.dataset.subtab===chatSubTab));renderChatMessages();});});
function renderChatMessages(){chatMessages.innerHTML='';const log=chatSubTab==='all'?chatHistory:whisperHistory;log.forEach(msg=>{const div=document.createElement('div');const mine=msg.id===socket?.id||msg.fromId===socket?.id;div.className='chat-msg '+(mine?'mine':'other');const nm=!mine?`<div class="chat-msg-name">${msg.name||msg.fromName}</div>`:'';const t=new Date(msg.time).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'});div.innerHTML=`${nm}${msg.message}<div class="chat-msg-time">${t}</div>`;chatMessages.appendChild(div);});chatMessages.scrollTop=chatMessages.scrollHeight;}
function sendChatPageMsg(){const m=chatPageInput.value.trim();if(!m||!socket)return;if(chatSubTab==='all')socket.emit('chat',{message:m});chatPageInput.value='';}
chatPageSend.addEventListener('click',sendChatPageMsg);chatPageInput.addEventListener('keydown',(e)=>{if(e.key==='Enter')sendChatPageMsg();});
const lobbyCreate=document.getElementById('lobbyCreate'),lobbyJoin=document.getElementById('lobbyJoin'),lobbyMyName=document.getElementById('lobbyMyName'),lobbyRoomName=document.getElementById('lobbyRoomName');
const lobbyCode=document.getElementById('lobbyCode'),lobbyJoinName=document.getElementById('lobbyJoinName'),lobbyJoinRoomName=document.getElementById('lobbyJoinRoomName');
const lobbyRoomCode=document.getElementById('lobbyRoomCode'),lobbyRoomTitle=document.getElementById('lobbyRoomTitle'),lobbyMembers=document.getElementById('lobbyMembers'),lobbyError=document.getElementById('lobbyError');
const lobbyCopyCode=document.getElementById('lobbyCopyCode');
lobbyCopyCode.addEventListener('click',()=>{if(!currentRoom)return;const text=`🐾 Hellowee 방 초대!\n방 이름: ${lobbyRoomTitle.textContent}\n방 코드: ${currentRoom}`;navigator.clipboard.writeText(text);lobbyCopyCode.textContent='✅ 복사됨';setTimeout(()=>{lobbyCopyCode.textContent='📋 초대링크';},1500);});
function saveLastRoom(code,roomName){try{const Store=require('electron-store');const s=new Store({name:'hellowee-auth'});s.set('lastRoom',{code,roomName});}catch(e){}}
lobbyCreate.addEventListener('click',()=>{const name=lobbyMyName.value.trim()||myChar.name;const roomName=lobbyRoomName.value.trim()||'Hellowee Room';myChar.name=name;if(socket)socket.disconnect();connectSocket();socket.on('connect',()=>{socket.emit('create-room',{roomName,name,parts:myChar.parts},(res)=>{if(res.success){currentRoom=res.code;saveLastRoom(res.code,roomName);updateLobbyUI();switchPage('home');lobbyError.textContent='';}});});});
lobbyJoin.addEventListener('click',()=>{const code=lobbyCode.value.trim().toUpperCase(),roomName=lobbyJoinRoomName.value.trim(),name=lobbyJoinName.value.trim()||myChar.name;if(!code||!roomName){lobbyError.textContent='방 이름과 코드를 모두 입력해주세요';return;}myChar.name=name;if(socket)socket.disconnect();connectSocket();socket.on('connect',()=>{socket.emit('join-room',{code,roomName,name,parts:myChar.parts},(res)=>{if(res.success){currentRoom=res.code;saveLastRoom(res.code,roomName);updateLobbyUI();switchPage('home');lobbyError.textContent='';}else{lobbyError.textContent=res.error;}});});});
function updateLobbyUI(){lobbyRoomCode.textContent=currentRoom||'---';lobbyMembers.innerHTML='';if(currentRoom){const me=document.createElement('div');me.className='lobby-member';me.innerHTML=`<div class="lobby-member-left"><span class="lobby-member-dot"></span> ${myChar.name} (나)${isRoomOwner?' 👑':''}</div>`;lobbyMembers.appendChild(me);Object.entries(otherChars).forEach(([id,c])=>{const div=document.createElement('div');div.className='lobby-member';let statusTag=c.status?` <span style="font-size:9px;color:#888">${c.status}</span>`:'';let html=`<div class="lobby-member-left"><span class="lobby-member-dot"></span> ${c.name}${statusTag}</div>`;if(isRoomOwner){html+=`<div style="display:flex;gap:4px;"><button class="lobby-kick-btn" data-kick-id="${id}">강퇴</button><button class="lobby-kick-btn" data-transfer-id="${id}" style="border-color:#6C8EBF;color:#6C8EBF;">위임</button></div>`;}div.innerHTML=html;lobbyMembers.appendChild(div);});lobbyMembers.querySelectorAll('.lobby-kick-btn[data-kick-id]').forEach(btn=>{btn.addEventListener('click',(e)=>{e.stopPropagation();const tid=btn.dataset.kickId;if(socket&&confirm(`${otherChars[tid]?.name}님을 강퇴할까요?`))socket.emit('kick-user',{targetId:tid});});});lobbyMembers.querySelectorAll('.lobby-kick-btn[data-transfer-id]').forEach(btn=>{btn.addEventListener('click',(e)=>{e.stopPropagation();const tid=btn.dataset.transferId;if(socket&&confirm(`${otherChars[tid]?.name}님에게 방장을 넘길까요?`))socket.emit('transfer-owner',{targetId:tid});});});}}
const customSection=document.querySelector('.custom-section');const labelMap={body:'피부',eyes:'눈',mouth:'입',hair:'헤어',clothes:'옷',accessory:'악세서리'};
LAYER_ORDER.forEach(layer=>{const row=document.createElement('div');row.className='custom-row';const label=document.createElement('div');label.className='custom-label';label.textContent=labelMap[layer];row.appendChild(label);const wrap=document.createElement('div');wrap.className='custom-options';PARTS_OPTIONS[layer].forEach(opt=>{const btn=document.createElement('button');btn.className='custom-btn';if(myChar.parts[layer]===opt)btn.classList.add('active');btn.textContent=opt;btn.addEventListener('click',()=>{myChar.parts[layer]=opt;wrap.querySelectorAll('.custom-btn').forEach(b=>b.classList.remove('active'));btn.classList.add('active');if(socket)socket.emit('update-parts',myChar.parts);});wrap.appendChild(btn);});row.appendChild(wrap);customSection.appendChild(row);});
const togglePin=document.getElementById('togglePin'),toggleAttention=document.getElementById('toggleAttention'),toggleBubble=document.getElementById('toggleBubble'),toggleSound=document.getElementById('toggleSound');
const settingsLeave=document.getElementById('settingsLeave'),settingsNickname=document.getElementById('settingsNickname'),settingsTutorial=document.getElementById('settingsTutorial');
togglePin.addEventListener('click',()=>{settingPin=!settingPin;togglePin.classList.toggle('on',settingPin);ipcRenderer.send('toggle-pin');});
toggleAttention.addEventListener('click',()=>{settingAttention=!settingAttention;toggleAttention.classList.toggle('on',settingAttention);});
toggleBubble.addEventListener('click',()=>{settingBubble=!settingBubble;toggleBubble.classList.toggle('on',settingBubble);});
toggleSound.addEventListener('click',()=>{settingSound=!settingSound;toggleSound.classList.toggle('on',settingSound);});
settingsLeave.addEventListener('click',()=>{if(socket)socket.disconnect();currentRoom=null;isRoomOwner=false;try{const Store=require('electron-store');const s=new Store({name:'hellowee-auth'});s.delete('lastRoom');}catch(e){}Object.keys(otherChars).forEach(id=>{otherChars[id].el.remove();otherChars[id].nameEl.remove();delete otherChars[id];});chatHistory=[];whisperHistory=[];updateLobbyUI();switchPage('lobby');});
const nicknameModal=document.getElementById('nicknameModal'),nicknameInput=document.getElementById('nicknameInput'),nicknameCancel=document.getElementById('nicknameCancel'),nicknameConfirm=document.getElementById('nicknameConfirm');
settingsNickname.addEventListener('click',()=>{nicknameInput.value=myChar.name;nicknameModal.classList.add('visible');});
nicknameCancel.addEventListener('click',()=>nicknameModal.classList.remove('visible'));
nicknameConfirm.addEventListener('click',()=>{const n=nicknameInput.value.trim();if(n){myChar.name=n;document.getElementById('settingsNicknameVal').textContent=n;nicknameModal.classList.remove('visible');}});
const statusContainer=document.getElementById('statusContainer');
if(statusContainer){STATUS_LIST.forEach(s=>{const btn=document.createElement('button');btn.textContent=s;btn.style.cssText='padding:5px 10px;border-radius:99px;border:1px solid #2a2a35;background:#1a1a22;color:#aaa;font-size:10px;cursor:pointer;margin:2px;';btn.addEventListener('click',()=>{myChar.status=s;if(socket)socket.emit('update-status',{status:s});statusContainer.querySelectorAll('button').forEach(b=>b.style.borderColor='#2a2a35');btn.style.borderColor='#6C8EBF';});statusContainer.appendChild(btn);});}
settingsTutorial.addEventListener('click',()=>{closePhone();Tutorial.reset();startTutorial();});
ipcRenderer.on('pin-status',(ev,p)=>{settingPin=p;togglePin.classList.toggle('on',p);});ipcRenderer.send('get-pin-status');
let tutorial=null;
function startTutorial(){tutorial=new Tutorial({onStep:(step,i)=>{playSound('click');},onFinish:()=>{tutorial=null;openPhone('lobby');},onSkip:()=>{tutorial=null;openPhone('lobby');},});tutorial.start();}
const activeBubbles=[];
function showBubble(cx,cy,msg,type){if(!settingBubble)return null;const b=document.createElement('div');b.className='bubble'+(type==='whisper'?' whisper':'');b.textContent=msg;b.style.left=(cx+DISPLAY_SIZE/2)+'px';b.style.top=(cy-40)+'px';document.body.appendChild(b);setTimeout(()=>{b.style.opacity='0';b.style.transition='opacity 0.3s';setTimeout(()=>b.remove(),300);},BUBBLE_DURATION);return b;}
function createTrackedBubble(g,msg,type){const p=g();const b=showBubble(p.x,p.y,msg,type);if(!b)return;const t={el:b,charGetter:g};activeBubbles.push(t);setTimeout(()=>{const i=activeBubbles.indexOf(t);if(i>-1)activeBubbles.splice(i,1);},BUBBLE_DURATION+300);}
function updateBubbles(){activeBubbles.forEach(b=>{if(!b.el.parentElement)return;const p=b.charGetter();b.el.style.left=(p.x+DISPLAY_SIZE/2)+'px';b.el.style.top=(p.y-40)+'px';});if(activeEmptyBubble?.updatePos)activeEmptyBubble.updatePos();}
function showAlert(){alertBadge.style.display='block';alertBadge.textContent=isAttentionMode()?'!!':'!';alertBadge.style.background=isAttentionMode()?'#ff2020':'#ff4757';document.getElementById('badgeChat').classList.add('show');playSound('alert');}
function hideAlert(){alertBadge.style.display='none';unreadChat=0;unreadWhisper=0;hasGrabbedMouse=false;document.getElementById('badgeChat').classList.remove('show');}
function updateAlertPos(){alertBadge.style.left=(myChar.x+DISPLAY_SIZE-5)+'px';alertBadge.style.top=(myChar.y-10)+'px';}
let interactCooldown=0;
function checkProximityInteract(){if(interactCooldown>0){interactCooldown--;return;}const mx=myChar.x+DISPLAY_SIZE/2;Object.values(otherChars).forEach(c=>{const cx=c.x+DISPLAY_SIZE/2;if(Math.abs(mx-cx)<INTERACT_DIST&&Math.abs(myChar.y-c.y)<DISPLAY_SIZE/2){myChar.state='wave';myChar.dir=cx>mx?1:-1;if(socket)socket.emit('interact',{});interactCooldown=300;setTimeout(()=>{if(myChar.state==='wave')myChar.state='idle';},1500);}});}
let walkTimer=0;
function randomWalk(){if(Math.random()<0.4){myChar.state='walk';myChar.dir=Math.random()<0.5?1:-1;myChar.vx=myChar.dir*1.5;walkTimer=60+Math.random()*120;}else{myChar.state='idle';myChar.vx=0;walkTimer=60+Math.random()*180;}}
function updateAttentionMode(){if(!isAttentionMode()||myChar.isGrabbed||myChar.forcedGrab||myChar.y<FLOOR_Y)return false;const cx=myChar.x+DISPLAY_SIZE/2,d=Math.abs(mousePos.x-cx);mouseIsIdle=(Date.now()-lastActivityTime)>MOUSE_IDLE_TIME;if(d>DISPLAY_SIZE/2){myChar.state='walk';myChar.dir=mousePos.x>cx?1:-1;myChar.vx=myChar.dir*CHASE_SPEED;}else{myChar.vx=0;if(mouseIsIdle&&!hasGrabbedMouse){hasGrabbedMouse=true;myChar.state='grabbed';myChar.attentionGrab=true;myChar.forcedGrab=true;myChar.x=mousePos.x-DISPLAY_SIZE/2;myChar.y=mousePos.y-DISPLAY_SIZE/2;setTimeout(()=>openPhone('chat'),500);}else if(!mouseIsIdle)myChar.state='idle';}return true;}
let lastTime=0;
function loop(ts){const dt=ts-lastTime;lastTime=ts;if(!myChar.isGrabbed&&!myChar.forcedGrab){if(myChar.y<FLOOR_Y){myChar.vy+=GRAVITY;if(myChar.state!=='thrown')myChar.state='fall';}else{myChar.y=FLOOR_Y;myChar.vy=0;if(myChar.state==='fall'||myChar.state==='thrown'){playSound('land');myChar.state='land';myChar.vx=0;setTimeout(()=>{myChar.state='idle';randomWalk();},300);}if(!updateAttentionMode()&&!RANDOM_ACTIONS.includes(myChar.state)){walkTimer--;if(walkTimer<=0&&myChar.state!=='land')randomWalk();}myChar.x+=myChar.vx;checkProximityInteract();}myChar.y+=myChar.vy;myChar.x=Math.max(0,Math.min(window.innerWidth-DISPLAY_SIZE,myChar.x));myChar.y=Math.min(FLOOR_Y,myChar.y);}else if(myChar.attentionGrab){myChar.x=mousePos.x-DISPLAY_SIZE/2;myChar.y=mousePos.y-DISPLAY_SIZE/2;}myChar.frameTimer+=dt;if(myChar.frameTimer>1000/FPS){myChar.frameTimer=0;myChar.frame=(myChar.frame+1)%(ANIM_FRAMES[myChar.state]||2);}renderChar(myCtx,myEl,myChar);updateAlertPos();updateBubbles();Object.values(otherChars).forEach(c=>{if(c.ctx){renderChar(c.ctx,c.el,c);c.nameEl.style.left=(c.x+DISPLAY_SIZE/2)+'px';c.nameEl.style.top=(c.y-18)+'px';}});if(socket&&socket.connected){socket.volatile.emit('move',{x:myChar.x,y:myChar.y,state:myChar.state,dir:myChar.dir,frame:myChar.frame});}requestAnimationFrame(loop);}
function animateLeave(id){const c=otherChars[id];if(!c)return;c.state='wave';createTrackedBubble(()=>({x:c.x,y:c.y}),'👋 안녕~','chat');playSound('leave');setTimeout(()=>{if(c.el){c.el.style.transition='opacity 0.5s';c.el.style.opacity='0';}if(c.nameEl){c.nameEl.style.transition='opacity 0.5s';c.nameEl.style.opacity='0';}setTimeout(()=>{if(c.el)c.el.remove();if(c.nameEl)c.nameEl.remove();delete otherChars[id];updateLobbyUI();},500);},WAVE_LEAVE_DURATION);}
let socket;
function connectSocket(){socket=io(SERVER_URL);
  socket.on('room-info',({code,name,isOwner})=>{currentRoom=code;isRoomOwner=isOwner;lobbyRoomCode.textContent=code;lobbyRoomTitle.textContent=name;updateLobbyUI();});
  socket.on('user-joined',({id,name,parts,status})=>{if(otherChars[id])return;playSound('join');const el=document.createElement('canvas');el.width=CHAR_SIZE;el.height=CHAR_SIZE;el.className='character';el.style.width=DISPLAY_SIZE+'px';el.style.height=DISPLAY_SIZE+'px';document.body.appendChild(el);const nameEl=document.createElement('div');nameEl.className='nameplate';nameEl.textContent=name;document.body.appendChild(nameEl);otherChars[id]={x:Math.random()*(window.innerWidth-DISPLAY_SIZE),y:FLOOR_Y,vx:0,vy:0,state:'idle',dir:1,frame:0,frameTimer:0,name,status:status||'',parts:parts||{},el,ctx:el.getContext('2d'),nameEl};el.addEventListener('mousedown',(e)=>{e.stopPropagation();mouseDownPos={x:e.clientX,y:e.clientY};dragTarget=id;dragOffset.x=e.clientX-otherChars[id].x;dragOffset.y=e.clientY-otherChars[id].y;isDragging=false;dragStartTime=Date.now();ipcRenderer.send('set-ignore-mouse',false);});updateLobbyUI();});
  socket.on('user-parts-updated',({id,parts})=>{if(otherChars[id])otherChars[id].parts=parts;});
  socket.on('user-status-updated',({id,status})=>{if(otherChars[id]){otherChars[id].status=status;updateLobbyUI();}});
  socket.on('user-moved',({id,x,y,state,dir,frame})=>{if(otherChars[id])Object.assign(otherChars[id],{x,y,state,dir,frame});});
  socket.on('user-leaving',({id})=>{animateLeave(id);});
  socket.on('user-left',({id,type})=>{if(type==='kicked'&&otherChars[id]){otherChars[id].el.remove();otherChars[id].nameEl.remove();delete otherChars[id];updateLobbyUI();}});
  socket.on('kicked',({reason})=>{alert(reason);currentRoom=null;isRoomOwner=false;Object.keys(otherChars).forEach(id=>{otherChars[id].el.remove();otherChars[id].nameEl.remove();delete otherChars[id];});switchPage('lobby');});
  socket.on('owner-changed',({newOwnerId,newOwnerName})=>{isRoomOwner=(newOwnerId===socket.id);updateLobbyUI();createTrackedBubble(()=>({x:myChar.x,y:myChar.y}),`👑 ${newOwnerName}님이 새 방장!`,'chat');});
  socket.on('chat-message',(data)=>{chatHistory.push(data);if(data.id===socket.id)createTrackedBubble(()=>({x:myChar.x,y:myChar.y}),data.message,'chat');else if(otherChars[data.id]){createTrackedBubble(()=>({x:otherChars[data.id].x,y:otherChars[data.id].y}),data.message,'chat');unreadChat++;showAlert();playSound('chat');}if(phone.classList.contains('visible')&&currentPage==='chat'&&chatSubTab==='all'){renderChatMessages();unreadChat=0;}});
  socket.on('whisper-message',(data)=>{whisperHistory.push(data);if(data.fromId===socket.id)createTrackedBubble(()=>({x:myChar.x,y:myChar.y}),data.message,'whisper');else if(otherChars[data.fromId]){createTrackedBubble(()=>({x:otherChars[data.fromId].x,y:otherChars[data.fromId].y}),data.message,'whisper');unreadWhisper++;showAlert();playSound('whisper');}if(phone.classList.contains('visible')&&currentPage==='chat'&&chatSubTab==='whisper'){renderChatMessages();unreadWhisper=0;}});
  socket.on('chat-history',(log)=>{chatHistory=log;});socket.on('whisper-history',(log)=>{whisperHistory=log;});
  socket.on('force-grabbed',()=>{myChar.forcedGrab=true;myChar.state='grabbed';myChar.vx=0;myChar.vy=0;playSound('grab');});
  socket.on('char-dragged',({targetId,x,y})=>{if(targetId===socket.id){myChar.x=x;myChar.y=y;}else if(otherChars[targetId]){otherChars[targetId].x=x;otherChars[targetId].y=y;otherChars[targetId].state='grabbed';}});
  socket.on('force-thrown',({vx,vy})=>{myChar.forcedGrab=false;myChar.attentionGrab=false;myChar.state='thrown';myChar.vx=vx;myChar.vy=vy;playSound('throw');});
  socket.on('force-dropped',()=>{myChar.forcedGrab=false;myChar.attentionGrab=false;myChar.state='fall';myChar.vy=1;myChar.vx=0;});
  socket.on('char-thrown',({targetId})=>{if(otherChars[targetId])otherChars[targetId].state='fall';});
  socket.on('char-dropped',({targetId})=>{if(otherChars[targetId])otherChars[targetId].state='fall';});
  socket.on('char-grabbed',({targetId})=>{if(otherChars[targetId])otherChars[targetId].state='grabbed';});
}
requestAnimationFrame(loop);
